---
- hosts: all
  connection: local
  user: remote
  become: true
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Create a virtual machine on given ESXi hostname
      vmware_guest:
        validate_certs: False
        hostname: "{{ esx_ipaddr }}"
        username: "{{ esx_user }}"
        password: "{{ esx_password }}"
        validate_certs: no
        folder: /vm
        esxi_hostname: "{{ esx_hostname }}"
        name: "{{ inventory_hostname }}"
        state: poweredon
        guest_id: centos7_64Guest

        disk:
        - size_gb: "{{ disk }}"
          type: thin
          datastore: "{{ datastore_name }}"
        hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpu }}"
          scsi: paravirtual
        cdrom:
          type: iso
          iso_path: "{{ iso_path }}"
        networks:
        - name: VMM Network
          device_type: vmxnet3
        - name: VMW Network
          device_type: vmxnet3

