#http://tsujitaku50.hatenablog.com/entry/2017/03/29/192845
# Javaがインストールされているか確認
- name: javaの存在確認
  shell: which java
  register: java_which
  failed_when: java_which.rc not in [0, 1]


# javaがインストールされていない場合, Javaをインストール
- name: OpenJDK11のインストール
  yum: name=java-11-openjdk-devel state=present
  when: java_which.rc == 1