---
- hosts: all
  connection: local
  user: remote
  sudo: true
  gather_facts: false

  vars:
    esx_hostname: 'ESXI-HOST1'
    esx_ipaddr: '192.168.182.116'
    esx_user: 'root'
    esx_password: 'Password@1234'
    datastore_name: 'datastore1'
    iso_path: 'datastore1/osimage/CentOS-7-KickStart.iso'

  tasks:
    - vsphere_guest:
        vcenter_hostname: "{{ esx_ipaddr }}"
        username: "{{ esx_user }}"
        password: "{{ esx_password }}"
        guest: "{{ inventory_hostname }}"
        state: powered_on
        validate_certs: False

        vm_hw_version: vmx-08
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
        vm_disk:
          disk1:
            size_gb: "{{ disk }}"
            type: thin
            datastore: "{{ datastore_name }}"
        vm_nic:
          nic1:
            type: vmxnet3
            network: VM Network
            network_type: standard
          nic2:
            type: vmxnet3
            network: VM Control Network
            network_type: standard
        vm_hardware:
          memory_mb: "{{ memory }}"
          osid: centos7_64Guest
          num_cpus: "{{ cpu }}"
          scsi: paravirtual
          vm_cdrom:
            type: "iso"
            iso_path: "{{ iso_path }}"
        esxi:
          datacenter: ha-datacenter
          hostname: "{{ esx_hostname }}"

